version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Thamilabkr4&
      MYSQL_DATABASE: cinema
      MYSQL_USER: Thamila_Achat
      MYSQL_PASSWORD: Thamilabkr4&
    ports:
      - "7052:7052"  # Assurez-vous que le port correspond à celui de votre base de données
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    depends_on:
      - mysql-db
    environment:
      - PMA_HOST=mysql-db

volumes:
  mysql-data:
    driver: local
